# UFO Landing Site - Small Scout Ship - 30x30
# Small alien craft with scorched landing zone

[metadata]
id = "ufo_scout_landing"
name = "Small Scout UFO Landing"
description = "30x30 landing site with small UFO craft and burned terrain"
width = 30
height = 30
group = 10
tags = "ufo, alien, landing, combat"
author = "XCOM Simple Team"
difficulty = 3

[tiles]
# Scorched earth perimeter (landing burn marks)
"10_8" = "SCORCH_MARK"
"11_8" = "SCORCH_MARK"
"12_8" = "SCORCH_MARK"
"13_8" = "SCORCH_MARK"
"14_8" = "SCORCH_MARK"
"15_8" = "SCORCH_MARK"
"16_8" = "SCORCH_MARK"
"17_8" = "SCORCH_MARK"
"18_8" = "SCORCH_MARK"
"19_8" = "SCORCH_MARK"

"9_9" = "SCORCH_MARK"
"20_9" = "SCORCH_MARK"

"8_10" = "SCORCH_MARK"
"9_10" = "SCORCH_MARK"
"20_10" = "SCORCH_MARK"
"21_10" = "SCORCH_MARK"

"8_11" = "SCORCH_MARK"
"21_11" = "SCORCH_MARK"

"7_12" = "SCORCH_MARK"
"8_12" = "SCORCH_MARK"
"21_12" = "SCORCH_MARK"
"22_12" = "SCORCH_MARK"

"7_13" = "SCORCH_MARK"
"22_13" = "SCORCH_MARK"

"7_14" = "SCORCH_MARK"
"22_14" = "SCORCH_MARK"

"7_15" = "SCORCH_MARK"
"22_15" = "SCORCH_MARK"

"7_16" = "SCORCH_MARK"
"22_16" = "SCORCH_MARK"

"7_17" = "SCORCH_MARK"
"22_17" = "SCORCH_MARK"

"7_18" = "SCORCH_MARK"
"8_18" = "SCORCH_MARK"
"21_18" = "SCORCH_MARK"
"22_18" = "SCORCH_MARK"

"8_19" = "SCORCH_MARK"
"21_19" = "SCORCH_MARK"

"8_20" = "SCORCH_MARK"
"9_20" = "SCORCH_MARK"
"20_20" = "SCORCH_MARK"
"21_20" = "SCORCH_MARK"

"9_21" = "SCORCH_MARK"
"20_21" = "SCORCH_MARK"

"10_22" = "SCORCH_MARK"
"11_22" = "SCORCH_MARK"
"12_22" = "SCORCH_MARK"
"13_22" = "SCORCH_MARK"
"14_22" = "SCORCH_MARK"
"15_22" = "SCORCH_MARK"
"16_22" = "SCORCH_MARK"
"17_22" = "SCORCH_MARK"
"18_22" = "SCORCH_MARK"
"19_22" = "SCORCH_MARK"

# UFO Hull (main body)
"12_10" = "WALL_ALIEN_HULL"
"13_10" = "WALL_ALIEN_HULL"
"14_10" = "WALL_ALIEN_HULL"
"15_10" = "WALL_ALIEN_HULL"
"16_10" = "WALL_ALIEN_HULL"
"17_10" = "WALL_ALIEN_HULL"

"11_11" = "WALL_ALIEN_HULL"
"18_11" = "WALL_ALIEN_HULL"

"10_12" = "WALL_ALIEN_HULL"
"19_12" = "WALL_ALIEN_HULL"

"10_13" = "WALL_ALIEN_HULL"
"19_13" = "WALL_ALIEN_HULL"

"9_14" = "WALL_ALIEN_HULL"
"20_14" = "WALL_ALIEN_HULL"

"9_15" = "WALL_ALIEN_HULL"
"14_15" = "DOOR_ALIEN"
"15_15" = "DOOR_ALIEN"
"20_15" = "WALL_ALIEN_HULL"

"9_16" = "WALL_ALIEN_HULL"
"20_16" = "WALL_ALIEN_HULL"

"10_17" = "WALL_ALIEN_HULL"
"19_17" = "WALL_ALIEN_HULL"

"10_18" = "WALL_ALIEN_HULL"
"19_18" = "WALL_ALIEN_HULL"

"11_19" = "WALL_ALIEN_HULL"
"18_19" = "WALL_ALIEN_HULL"

"12_20" = "WALL_ALIEN_HULL"
"13_20" = "WALL_ALIEN_HULL"
"14_20" = "WALL_ALIEN_HULL"
"15_20" = "WALL_ALIEN_HULL"
"16_20" = "WALL_ALIEN_HULL"
"17_20" = "WALL_ALIEN_HULL"

# UFO Interior floor
"12_11" = "FLOOR_ALIEN_ALLOY"
"13_11" = "FLOOR_ALIEN_ALLOY"
"14_11" = "FLOOR_ALIEN_ALLOY"
"15_11" = "FLOOR_ALIEN_ALLOY"
"16_11" = "FLOOR_ALIEN_ALLOY"
"17_11" = "FLOOR_ALIEN_ALLOY"

"11_12" = "FLOOR_ALIEN_ALLOY"
"12_12" = "FLOOR_ALIEN_ALLOY"
"13_12" = "FLOOR_ALIEN_ALLOY"
"16_12" = "FLOOR_ALIEN_ALLOY"
"17_12" = "FLOOR_ALIEN_ALLOY"
"18_12" = "FLOOR_ALIEN_ALLOY"

"11_13" = "FLOOR_ALIEN_ALLOY"
"12_13" = "FLOOR_ALIEN_ALLOY"
"13_13" = "FLOOR_ALIEN_ALLOY"
"14_13" = "FLOOR_ALIEN_ALLOY"
"15_13" = "FLOOR_ALIEN_ALLOY"
"16_13" = "FLOOR_ALIEN_ALLOY"
"17_13" = "FLOOR_ALIEN_ALLOY"
"18_13" = "FLOOR_ALIEN_ALLOY"

"10_14" = "FLOOR_ALIEN_ALLOY"
"12_14" = "FLOOR_ALIEN_ALLOY"
"13_14" = "FLOOR_ALIEN_ALLOY"
"14_14" = "FLOOR_ALIEN_ALLOY"
"15_14" = "FLOOR_ALIEN_ALLOY"
"16_14" = "FLOOR_ALIEN_ALLOY"
"17_14" = "FLOOR_ALIEN_ALLOY"
"19_14" = "FLOOR_ALIEN_ALLOY"

"10_15" = "FLOOR_ALIEN_ALLOY"
"11_15" = "FLOOR_ALIEN_ALLOY"
"12_15" = "FLOOR_ALIEN_ALLOY"
"13_15" = "FLOOR_ALIEN_ALLOY"
"16_15" = "FLOOR_ALIEN_ALLOY"
"17_15" = "FLOOR_ALIEN_ALLOY"
"18_15" = "FLOOR_ALIEN_ALLOY"
"19_15" = "FLOOR_ALIEN_ALLOY"

"10_16" = "FLOOR_ALIEN_ALLOY"
"11_16" = "FLOOR_ALIEN_ALLOY"
"13_16" = "FLOOR_ALIEN_ALLOY"
"14_16" = "FLOOR_ALIEN_ALLOY"
"15_16" = "FLOOR_ALIEN_ALLOY"
"16_16" = "FLOOR_ALIEN_ALLOY"
"18_16" = "FLOOR_ALIEN_ALLOY"
"19_16" = "FLOOR_ALIEN_ALLOY"

"11_17" = "FLOOR_ALIEN_ALLOY"
"12_17" = "FLOOR_ALIEN_ALLOY"
"13_17" = "FLOOR_ALIEN_ALLOY"
"16_17" = "FLOOR_ALIEN_ALLOY"
"17_17" = "FLOOR_ALIEN_ALLOY"
"18_17" = "FLOOR_ALIEN_ALLOY"

"11_18" = "FLOOR_ALIEN_ALLOY"
"12_18" = "FLOOR_ALIEN_ALLOY"
"13_18" = "FLOOR_ALIEN_ALLOY"
"14_18" = "FLOOR_ALIEN_ALLOY"
"15_18" = "FLOOR_ALIEN_ALLOY"
"16_18" = "FLOOR_ALIEN_ALLOY"
"17_18" = "FLOOR_ALIEN_ALLOY"
"18_18" = "FLOOR_ALIEN_ALLOY"

"12_19" = "FLOOR_ALIEN_ALLOY"
"13_19" = "FLOOR_ALIEN_ALLOY"
"14_19" = "FLOOR_ALIEN_ALLOY"
"15_19" = "FLOOR_ALIEN_ALLOY"
"16_19" = "FLOOR_ALIEN_ALLOY"
"17_19" = "FLOOR_ALIEN_ALLOY"

# Navigation console
"14_12" = "CONSOLE_NAVIGATION"
"15_12" = "CONSOLE_NAVIGATION"

# Power core
"14_17" = "POWER_SOURCE"
"15_17" = "POWER_SOURCE"

# Stasis pods
"11_14" = "POD_STASIS"
"18_14" = "POD_STASIS"

# Equipment
"12_16" = "EQUIPMENT_ALIEN"
"17_16" = "EQUIPMENT_ALIEN"
