# Urban Small Block 01 - Single building with street
# 15x15 tiles - Basic city block with brick building

[metadata]
id = "urban_small_01"
name = "Small City Building"
description = "Small brick building with sidewalk and street access"
width = 15
height = 15
group = 1
tags = "urban, building, small, civilian"
author = "XCOM Simple Team"
difficulty = 1

[tiles]
# Street (bottom rows)
"0_0" = "ROAD_ASPHALT"
"1_0" = "ROAD_ASPHALT"
"2_0" = "ROAD_ASPHALT"
"3_0" = "ROAD_ASPHALT"
"4_0" = "ROAD_ASPHALT"
"5_0" = "ROAD_ASPHALT"
"6_0" = "ROAD_ASPHALT"
"7_0" = "ROAD_ASPHALT"
"8_0" = "ROAD_ASPHALT"
"9_0" = "ROAD_ASPHALT"
"10_0" = "ROAD_ASPHALT"
"11_0" = "ROAD_ASPHALT"
"12_0" = "ROAD_ASPHALT"
"13_0" = "ROAD_ASPHALT"
"14_0" = "ROAD_ASPHALT"

# Sidewalk
"0_1" = "SIDEWALK_CONCRETE"
"1_1" = "SIDEWALK_CONCRETE"
"2_1" = "SIDEWALK_CONCRETE"
"3_1" = "SIDEWALK_CONCRETE"
"4_1" = "SIDEWALK_CONCRETE"
"5_1" = "SIDEWALK_CONCRETE"
"6_1" = "SIDEWALK_CONCRETE"
"7_1" = "SIDEWALK_CONCRETE"
"8_1" = "SIDEWALK_CONCRETE"
"9_1" = "SIDEWALK_CONCRETE"
"10_1" = "SIDEWALK_CONCRETE"
"11_1" = "SIDEWALK_CONCRETE"
"12_1" = "SIDEWALK_CONCRETE"
"13_1" = "SIDEWALK_CONCRETE"
"14_1" = "SIDEWALK_CONCRETE"

# Building exterior walls (rows 2-10)
"2_2" = "WALL_BRICK"
"3_2" = "WALL_BRICK"
"4_2" = "WALL_BRICK"
"5_2" = "WALL_BRICK"
"6_2" = "DOOR_WOOD"
"7_2" = "WALL_BRICK"
"8_2" = "WALL_BRICK"
"9_2" = "WALL_BRICK"
"10_2" = "WALL_BRICK"
"11_2" = "WALL_BRICK"
"12_2" = "WALL_BRICK"

"2_3" = "WALL_BRICK"
"12_3" = "WALL_BRICK"

"2_4" = "WALL_BRICK"
"4_4" = "WINDOW_GLASS"
"8_4" = "WINDOW_GLASS"
"12_4" = "WALL_BRICK"

"2_5" = "WALL_BRICK"
"12_5" = "WALL_BRICK"

"2_6" = "WALL_BRICK"
"12_6" = "WALL_BRICK"

"2_7" = "WALL_BRICK"
"4_7" = "WINDOW_GLASS"
"8_7" = "WINDOW_GLASS"
"12_7" = "WALL_BRICK"

"2_8" = "WALL_BRICK"
"12_8" = "WALL_BRICK"

"2_9" = "WALL_BRICK"
"12_9" = "WALL_BRICK"

"2_10" = "WALL_BRICK"
"3_10" = "WALL_BRICK"
"4_10" = "WALL_BRICK"
"5_10" = "WALL_BRICK"
"6_10" = "WALL_BRICK"
"7_10" = "WALL_BRICK"
"8_10" = "WALL_BRICK"
"9_10" = "WALL_BRICK"
"10_10" = "WALL_BRICK"
"11_10" = "WALL_BRICK"
"12_10" = "WALL_BRICK"

# Interior floor
"3_3" = "FLOOR_TILE"
"4_3" = "FLOOR_TILE"
"5_3" = "FLOOR_TILE"
"6_3" = "FLOOR_TILE"
"7_3" = "FLOOR_TILE"
"8_3" = "FLOOR_TILE"
"9_3" = "FLOOR_TILE"
"10_3" = "FLOOR_TILE"
"11_3" = "FLOOR_TILE"

"3_4" = "FLOOR_TILE"
"5_4" = "FLOOR_TILE"
"6_4" = "FLOOR_TILE"
"7_4" = "FLOOR_TILE"
"9_4" = "FLOOR_TILE"
"10_4" = "FLOOR_TILE"
"11_4" = "FLOOR_TILE"

"3_5" = "FLOOR_TILE"
"4_5" = "FLOOR_TILE"
"5_5" = "FLOOR_TILE"
"6_5" = "FLOOR_TILE"
"7_5" = "FLOOR_TILE"
"8_5" = "FLOOR_TILE"
"9_5" = "FLOOR_TILE"
"10_5" = "FLOOR_TILE"
"11_5" = "FLOOR_TILE"

"3_6" = "FLOOR_TILE"
"4_6" = "FLOOR_TILE"
"5_6" = "FLOOR_TILE"
"6_6" = "FLOOR_TILE"
"7_6" = "FLOOR_TILE"
"8_6" = "FLOOR_TILE"
"9_6" = "FLOOR_TILE"
"10_6" = "FLOOR_TILE"
"11_6" = "FLOOR_TILE"

"3_7" = "FLOOR_TILE"
"5_7" = "FLOOR_TILE"
"6_7" = "FLOOR_TILE"
"7_7" = "FLOOR_TILE"
"9_7" = "FLOOR_TILE"
"10_7" = "FLOOR_TILE"
"11_7" = "FLOOR_TILE"

"3_8" = "FLOOR_TILE"
"4_8" = "FLOOR_TILE"
"5_8" = "FLOOR_TILE"
"6_8" = "FLOOR_TILE"
"7_8" = "FLOOR_TILE"
"8_8" = "FLOOR_TILE"
"9_8" = "FLOOR_TILE"
"10_8" = "FLOOR_TILE"
"11_8" = "FLOOR_TILE"

"3_9" = "FLOOR_TILE"
"4_9" = "FLOOR_TILE"
"5_9" = "FLOOR_TILE"
"6_9" = "FLOOR_TILE"
"7_9" = "FLOOR_TILE"
"8_9" = "FLOOR_TILE"
"9_9" = "FLOOR_TILE"
"10_9" = "FLOOR_TILE"
"11_9" = "FLOOR_TILE"
