# Phase 0: Shadow War (1996-1999)
# Human factions, covert operations, and supernatural threats

[phase]
id = "phase0_shadow_war"
name = "Shadow War"
description = "Human factions, covert operations, and supernatural outbreaks. Evidence suppression intensifies as subtle alien signs appear."
start_year = 1996
end_year = 1999
phase_number = 0
status = "investigation"

[timeline]
milestones = [
    "start_private_firm",
    "first_anomalies",
    "supernatural_outbreaks",
    "blackops_evidence",
    "alien_signatures",
    "build_network",
    "intelligence_spike",
    "formalize_xcom"
]

[factions]
active = [
    "faction_cult",
    "faction_blackops",
    "faction_supernatural",
    "faction_syndicate",
    "faction_mib"
]

[missions]
types = [
    "investigation",
    "containment",
    "suppression",
    "negotiation"
]

[enemy_types]
common = ["cult_member", "supernatural_entity"]
rare = ["early_scout"]

[technology]
available = [
    "investigation_techniques",
    "occult_knowledge",
    "basic_surveillance"
]

[gameplay]
tech_level = "conventional"
difficulty_scaling = 0.5
alien_visibility = "minimal"
