# Yellow Army - Unit Spritesheet Configuration
# This file defines which graphics to include and how many times to repeat each

army: yellow
name: "Yellow Army"
description: "Yellow army units for printing on A4 sheets"

# Print settings
print:
  format: "A4"
  dpi: 300
  width_px: 2480
  height_px: 3508
  margin_px: 50
  grid:
    columns: 10
    rows: 15
    total_items: 150

# Units to include in spritesheet
# Format: filename -> repetitions_in_output
units:
  - name: "archer"
    file: "yellow_archer.png"
    repetitions: 20
    width: 70
    height: 70

  - name: "balista"
    file: "yellow_balista.png"
    repetitions: 10
    width: 70
    height: 70

  - name: "cavalery"
    file: "yellow_cavalery.png"
    repetitions: 20
    width: 70
    height: 70

  - name: "dragon"
    file: "yellow_dragon.png"
    repetitions: 10
    width: 70
    height: 70

  - name: "footman"
    file: "yellow_footman.png"
    repetitions: 20
    width: 70
    height: 70

  - name: "frog"
    file: "yellow_frog.png"
    repetitions: 10
    width: 70
    height: 70

  - name: "harpy"
    file: "yellow_harpy.png"
    repetitions: 10
    width: 70
    height: 70

  - name: "kraken"
    file: "yellow_kraken.png"
    repetitions: 10
    width: 70
    height: 70

  - name: "pikeman"
    file: "yellow_pikeman.png"
    repetitions: 20
    width: 70
    height: 70

  - name: "worker"
    file: "yellow_worker.png"
    repetitions: 10
    width: 70
    height: 70

  - name: "dog"
    file: "yellow_dog.png"
    repetitions: 10
    width: 70
    height: 70
