[mod]
# Complete Example Mod - Demonstrates all modding capabilities
id = "example_complete"
name = "Complete Example Mod"
version = "1.0.0"
description = "Comprehensive example mod demonstrating all AlienFall modding capabilities including custom weapons, units, facilities, research, and missions."
author = "AlienFall Development Team"

[metadata]
category = "example"
tags = ["example", "weapons", "units", "facilities", "technology", "complete"]
documentation = "README.md"

[settings]
enabled = true
load_order = 100  # Load after core (priority 1) but early

# Content directories
[paths]
weapons = "weapons"
units = "units"
facilities = "facilities"
technology = "technology"

# Dependencies
[dependencies]
core = { version = ">=1.0.0", required = true }

# Mod compatibility
[compatibility]
min_game_version = "1.0.0"
max_game_version = "2.0.0"

# Content summary
[content]
weapons = 3
armor = 2
unit_classes = 2
units = 4
facilities = 3
technologies = 2
missions = 1

# Load hooks - called during mod initialization
[hooks]
on_load = "init.lua"
on_enable = "scripts/enable.lua"
on_disable = "scripts/disable.lua"

# Feature flags
[features]
custom_weapons = true
custom_units = true
custom_facilities = true
custom_research = true
custom_missions = true
balance_changes = false
