# Red Army - Unit Spritesheet Configuration
# This file defines which graphics to include and how many times to repeat each

army: red
name: "Red Army"
description: "Red army units for printing on A4 sheets"

# Print settings
print:
  format: "A4"
  dpi: 300
  width_px: 2480
  height_px: 3508
  margin_px: 50
  grid:
    columns: 10
    rows: 15
    total_items: 150

# Units to include in spritesheet
# Format: filename -> repetitions_in_output
units:
  - name: "archer"
    file: "red_archer.png"
    repetitions: 20
    width: 72
    height: 72

  - name: "balista"
    file: "red_balista.png"
    repetitions: 10
    width: 72
    height: 72

  - name: "cavalery"
    file: "red_cavalery.png"
    repetitions: 20
    width: 72
    height: 72

  - name: "dragon"
    file: "red_dragon.png"
    repetitions: 10
    width: 72
    height: 72

  - name: "footman"
    file: "red_footman.png"
    repetitions: 20
    width: 72
    height: 72

  - name: "frog"
    file: "red_frog.png"
    repetitions: 10
    width: 72
    height: 72

  - name: "harpy"
    file: "red_harpy.png"
    repetitions: 10
    width: 72
    height: 72

  - name: "kraken"
    file: "red_kraken.png"
    repetitions: 10
    width: 72
    height: 72

  - name: "pikeman"
    file: "red_pikeman.png"
    repetitions: 20
    width: 72
    height: 72

  - name: "worker"
    file: "red_worker.png"
    repetitions: 10
    width: 72
    height: 72

  - name: "dog"
    file: "red_dog.png"
    repetitions: 10
    width: 72
    height: 72
