# Urban Block MapBlock
# City block with building and roads

[metadata]
id = "urban_block_01"
name = "City Block"
description = "Urban area with roads and central building"
width = 15
height = 15
biome = "urban"
difficulty = 2
author = "System"
tags = "urban, building, roads, medium"

[tiles]
# Roads on edges (top)
"0_0" = "road"
"0_1" = "road"
"0_2" = "road"
"0_3" = "road"
"0_4" = "road"
"0_5" = "road"
"0_6" = "road"
"0_7" = "road"
"0_8" = "road"
"0_9" = "road"
"0_10" = "road"
"0_11" = "road"
"0_12" = "road"
"0_13" = "road"
"0_14" = "road"

# Roads on edges (bottom)
"14_0" = "road"
"14_1" = "road"
"14_2" = "road"
"14_3" = "road"
"14_4" = "road"
"14_5" = "road"
"14_6" = "road"
"14_7" = "road"
"14_8" = "road"
"14_9" = "road"
"14_10" = "road"
"14_11" = "road"
"14_12" = "road"
"14_13" = "road"
"14_14" = "road"

# Roads on edges (left)
"1_0" = "road"
"2_0" = "road"
"3_0" = "road"
"4_0" = "road"
"5_0" = "road"
"6_0" = "road"
"7_0" = "road"
"8_0" = "road"
"9_0" = "road"
"10_0" = "road"
"11_0" = "road"
"12_0" = "road"
"13_0" = "road"

# Roads on edges (right)
"1_14" = "road"
"2_14" = "road"
"3_14" = "road"
"4_14" = "road"
"5_14" = "road"
"6_14" = "road"
"7_14" = "road"
"8_14" = "road"
"9_14" = "road"
"10_14" = "road"
"11_14" = "road"
"12_14" = "road"
"13_14" = "road"

# Building walls (outer perimeter)
"4_4" = "wall"
"4_5" = "wall"
"4_6" = "wall"
"4_7" = "wall"
"4_8" = "wall"
"4_9" = "wall"
"4_10" = "wall"
"5_4" = "wall"
"5_10" = "wall"
"6_4" = "wall"
"6_10" = "wall"
"7_4" = "wall"
"7_10" = "wall"
"8_4" = "wall"
"8_10" = "wall"
"9_4" = "wall"
"9_10" = "wall"
"10_4" = "wall"
"10_5" = "wall"
"10_6" = "wall"
"10_7" = "door"
"10_8" = "wall"
"10_9" = "wall"
"10_10" = "wall"

# Building interior (floor)
"5_5" = "floor"
"5_6" = "floor"
"5_7" = "floor"
"5_8" = "floor"
"5_9" = "floor"
"6_5" = "floor"
"6_6" = "floor"
"6_7" = "floor"
"6_8" = "floor"
"6_9" = "floor"
"7_5" = "floor"
"7_6" = "floor"
"7_7" = "floor"
"7_8" = "floor"
"7_9" = "floor"
"8_5" = "floor"
"8_6" = "floor"
"8_7" = "floor"
"8_8" = "floor"
"8_9" = "floor"
"9_5" = "floor"
"9_6" = "floor"
"9_7" = "floor"
"9_8" = "floor"
"9_9" = "floor"
