# Urban Residential MapBlock
# Residential area with houses and yards

[metadata]
id = "urban_residential_01"
name = "Residential Block"
description = "Suburban area with small houses and fenced yards"
width = 15
height = 15
biome = "urban"
difficulty = 1
author = "System"
tags = "urban, residential, houses, easy"

[tiles]
# House 1 (top-left)
"2_2" = "wall"
"2_3" = "wall"
"2_4" = "wall"
"3_2" = "wall"
"3_4" = "wall"
"4_2" = "wall"
"4_3" = "door"
"4_4" = "wall"
"3_3" = "floor"

# House 1 yard fence
"1_1" = "fence"
"1_2" = "fence"
"1_3" = "fence"
"1_4" = "fence"
"1_5" = "fence"
"2_1" = "fence"
"2_5" = "fence"
"3_1" = "fence"
"3_5" = "fence"
"4_1" = "fence"
"4_5" = "fence"
"5_1" = "fence"
"5_2" = "fence"
"5_3" = "fence"
"5_4" = "fence"
"5_5" = "fence"

# House 2 (top-right)
"2_10" = "wall"
"2_11" = "wall"
"2_12" = "wall"
"3_10" = "wall"
"3_12" = "wall"
"4_10" = "wall"
"4_11" = "door"
"4_12" = "wall"
"3_11" = "floor"

# House 2 yard fence
"1_9" = "fence"
"1_10" = "fence"
"1_11" = "fence"
"1_12" = "fence"
"1_13" = "fence"
"2_9" = "fence"
"2_13" = "fence"
"3_9" = "fence"
"3_13" = "fence"
"4_9" = "fence"
"4_13" = "fence"
"5_9" = "fence"
"5_10" = "fence"
"5_11" = "fence"
"5_12" = "fence"
"5_13" = "fence"

# House 3 (bottom-left)
"10_2" = "wall"
"10_3" = "wall"
"10_4" = "wall"
"11_2" = "wall"
"11_4" = "wall"
"12_2" = "wall"
"12_3" = "door"
"12_4" = "wall"
"11_3" = "floor"

# House 3 yard fence
"9_1" = "fence"
"9_2" = "fence"
"9_3" = "fence"
"9_4" = "fence"
"9_5" = "fence"
"10_1" = "fence"
"10_5" = "fence"
"11_1" = "fence"
"11_5" = "fence"
"12_1" = "fence"
"12_5" = "fence"
"13_1" = "fence"
"13_2" = "fence"
"13_3" = "fence"
"13_4" = "fence"
"13_5" = "fence"

# House 4 (bottom-right)
"10_10" = "wall"
"10_11" = "wall"
"10_12" = "wall"
"11_10" = "wall"
"11_12" = "wall"
"12_10" = "wall"
"12_11" = "door"
"12_12" = "wall"
"11_11" = "floor"

# House 4 yard fence
"9_9" = "fence"
"9_10" = "fence"
"9_11" = "fence"
"9_12" = "fence"
"9_13" = "fence"
"10_9" = "fence"
"10_13" = "fence"
"11_9" = "fence"
"11_13" = "fence"
"12_9" = "fence"
"12_13" = "fence"
"13_9" = "fence"
"13_10" = "fence"
"13_11" = "fence"
"13_12" = "fence"
"13_13" = "fence"

# Street (center)
"7_0" = "road"
"7_1" = "road"
"7_2" = "road"
"7_3" = "road"
"7_4" = "road"
"7_5" = "road"
"7_6" = "road"
"7_7" = "road"
"7_8" = "road"
"7_9" = "road"
"7_10" = "road"
"7_11" = "road"
"7_12" = "road"
"7_13" = "road"
"7_14" = "road"

# Small trees in yards (avoiding conflicts)
"6_3" = "bushes"
"6_11" = "bushes"
"8_3" = "bushes"
"8_11" = "bushes"
