# Research Facility Definitions

[[facility]]
id = "research_lab"
name = "Research Laboratory"
description = "General scientific research facility"
type = "research"
width = 3
height = 2
cost = 1800
time_to_build = 9
maintenance_cost = 35
research_rate = 1.0
effect = "research_speed"

[[facility]]
id = "alien_research"
name = "Alien Research Lab"
description = "Dedicated alien technology research"
type = "research"
width = 3
height = 2
cost = 2500
time_to_build = 10
maintenance_cost = 50
research_rate = 1.5
specialization = "alien"

[[facility]]
id = "engineering_lab"
name = "Engineering Laboratory"
description = "Engineering and physics research"
type = "research"
width = 3
height = 2
cost = 2000
time_to_build = 9
maintenance_cost = 40
research_rate = 1.2
specialization = "engineering"

[[facility]]
id = "psionic_lab"
name = "Psionic Laboratory"
description = "Psionic research and training"
type = "research"
width = 2
height = 2
cost = 2200
time_to_build = 10
maintenance_cost = 45
research_rate = 1.3
specialization = "psionic"

[[facility]]
id = "chemistry_lab"
name = "Chemistry Laboratory"
description = "Chemical and biological research"
type = "research"
width = 3
height = 2
cost = 1900
time_to_build = 9
maintenance_cost = 38
research_rate = 1.1
specialization = "chemistry"
