# Alien Fall Mod Configuration

[mod]
id = "xcom_simple"
name = "Alien Fall"
version = "0.1.0"
author = "Alien Fall Team"
description = "Core content for Alien Fall - a turn-based tactical strategy game inspired by X-COM"
type = "content"
dependencies = []

[paths]
assets = "assets"
rules = "rules"
mapblocks = "mapblocks"
maps = "maps"
scripts = "scripts"

[content]
terrain_types = true
weapons = true
armours = true
unit_classes = true
mapblocks = true
assets = true

[settings]
enabled = true
load_order = 100
